# Generated by Django 5.2.4 on 2025-07-23 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cidade_customuser_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='core.pedido')),
            ],
        ),
    ]
