# Generated by Django 5.2.4 on 2025-07-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_avaliacaopedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaopedido',
            old_name='data_avaliacao',
            new_name='criado_em',
        ),
        migrations.AlterField(
            model_name='avaliacaopedido',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaopedido',
            name='nota',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
