# Generated by Django 5.2.4 on 2025-07-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_data_avaliacao_avaliacaopedido_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('boleto', 'Boleto'), ('cartao', 'Cartão de Crédito'), ('pix', 'PIX')], default='boleto', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
